### ISSUE TITLE
Error creating additional user with existing GID

### ISSUE THREAD

**Issue by Janfy** [Hermsi1337/docker-sshd#6]
Hi,

When specifying an additional user with UID:GID = 999:999, there is an error creating the new user because the group 999 exists:
```
[INFO] Applying configuration for additional users ...
[INFO]     desired shell is /bin/bash
[INFO]     'redmine:999:999'
adduser: unknown group redmine
```

Command executed:
```
docker run -it --rm --publish=1337:22 --env SSH_USERS="redmine:999:999" --name sshd hermsi/alpine-sshd
```

I think the error is here:

https://github.com/Hermsi1337/docker-sshd/blob/2dc325b59b84b609d5b39e89ed1646846b5241f0/entrypoint.sh#L131

The created user should used the GID provided in `SSH_USERS` instead of the username.

Fix:
```
getent passwd "${USER_NAME}" &>/dev/null || adduser -s "${USER_LOGIN_SHELL}" -D -u "${USER_UID}" -G "${USER_GID}" "${USER_NAME}" 
```

Thanks for your feedback.
Jean-Philippe.

**Comment by Hermsi1337** [comment]
Good catch sir.

That errors is thrown because the `GID` `999` is already present in the system - but with another name.  
I've changed the behaviour a bit: when you provide a `GID` which is already present, the image will now use the name of the present group assigned to that `GID` and print a `WARNING`.

PR inc.

**Comment by Hermsi1337** [comment]
You may check the new `latest`-image (:

I'd appreciate your feedback.

EDIT:
My provided "fix" may not provide the behaviour fitting to your intention.   
To suit your use-case you may just provide a different `GID` (=

Many thanks,  
Hermsi
